function catchError(error)
{
    console.log(error);
}

module.exports = catchError;